# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class Test111():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_wpisanie_w_google(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(1813, 1012)
        # time.sleep(1000)
        self.driver.find_element(By.XPATH, '//*[@id="L2AGLb"]/div').click()
        time.sleep(3)
        szukaj = self.driver.find_element(By.NAME, "q")
        szukaj.send_keys("selenium")
        szukaj.submit()
        assert self.driver.title == "selenium - Szukaj w Google"
        self.driver.save_screenshot('screenshot.png')
        time.sleep(3)
